### ISSUE TITLE
Добавить обнуление background-image

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.special#7]
![image](https://cloud.githubusercontent.com/assets/3684889/20389648/bffdffcc-acdb-11e6-89e5-61890dbfe96b.png)

На сайтах фоны могут задавать через background-image, которые не перекрыватются
Чтобы обработать все случаи, нужно дописать перекрывающее свойство.

```css
body.special-white, 
.special-white div, 
.special-white aside, 
.special-white footer, 
.special-white header, 
.special-white form, 
.special-white article {
    background-color: #121213 !important;
    background-image: none !important
}
```

Это нужно добавить во все цветовые гаммы
